CREATE TABLE NOTIFICA.USUARIO (
    idUsuario NUMBER PRIMARY KEY NOT NULL,
    nomeUsuario VARCHAR2(255) NOT NULL,
    numeroCelular VARCHAR2(20) NOT NULL,
    senhaUsuario VARCHAR2(255) NOT NULL,
    etniaUsuario VARCHAR2(50),
    dataNascimento DATE NOT NULL,
    classeSocial VARCHAR2(50),
    generoUsuario VARCHAR2(20),
    tipoUsuario VARCHAR2(50) NOT NULL
);

CREATE TABLE NOTIFICA.DENUNCIA (
    idDenuncia NUMBER PRIMARY KEY NOT NULL,
    descricao VARCHAR2(1000) NOT NULL,
    latitude NUMBER NOT NULL,
    longitude NUMBER NOT NULL,
    usuarioId NUMBER NOT NULL,
    dataHora TIMESTAMP NOT NULL,
    statusDenuncia VARCHAR2(20) NOT NULL,
    categoria VARCHAR2(20) NOT NULL,
    curtidas NUMBER,
    validarDenuncia NUMBER,
    FOREIGN KEY (usuarioId) REFERENCES NOTIFICA.USUARIO(idUsuario)
);


CREATE SEQUENCE NOTIFICA.SEQ_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE NOTIFICA.SEQ_DENUNCIA
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;