INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'João Silva', '123456789', 'senha123', 'BRANCA', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'A', 'MASCULINO', 'ADMIN');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Maria Oliveira', '987654321', 'senha456', 'PARDA', TO_DATE('1985-08-22', 'YYYY-MM-DD'), 'B', 'FEMININO', 'ADMIN');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Carlos Santos', '111222333', 'senha789', 'PRETA', TO_DATE('1978-11-10', 'YYYY-MM-DD'), 'C', 'MASCULINO', 'ADMIN');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Ana Souza', '555666777', 'senhaabc', 'AMARELO', TO_DATE('1995-03-28', 'YYYY-MM-DD'), 'D', 'FEMININO', 'ADMIN');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Pedro Lima', '999888777', 'senhaxyz', 'INDIGENA', TO_DATE('1980-09-17', 'YYYY-MM-DD'), 'E', 'MASCULINO', 'INDIVIDUAL');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Fernanda Pereira', '444333222', 'senhawxyz', 'BRANCA', TO_DATE('1992-07-03', 'YYYY-MM-DD'), 'E', 'FEMININO', 'INDIVIDUAL');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Ricardo Costa', '777888999', 'senhatest', 'PARDA', TO_DATE('1987-12-05', 'YYYY-MM-DD'), 'A', 'MASCULINO', 'INDIVIDUAL');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Juliana Almeida', '222111333', 'senhaxpto', 'PRETA', TO_DATE('1998-01-20', 'YYYY-MM-DD'), 'B', 'FEMININO', 'INDIVIDUAL');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Márcio Rocha', '666555444', 'senha123', 'AMARELO', TO_DATE('1983-06-14', 'YYYY-MM-DD'), 'E', 'MASCULINO', 'INDIVIDUAL');

INSERT INTO NOTIFICA.USUARIO VALUES (NOTIFICA.SEQ_USUARIO.NEXTVAL, 'Carolina Lima', '333444555', 'senha456', 'INDIGENA', TO_DATE('1994-04-07', 'YYYY-MM-DD'), 'C', 'FEMININO', 'INDIVIDUAL');

